I18n version
hisaotoriyama/fjord_books_for_rails pull request #1
Opened 2020-09-17 07:42 UTC by hisaotoriyama

i18n対応化いたしましたので内容ご確認お願いいたします。

2020-09-21 06:48 UTC, betachelsea requested changes
### PullRequestのタイトルについて
「I18n version」という表現になっていますが、"i18n" は internationalization(国際化・他言語化)を意味しているため、i18n自体にはバージョンがあがったりさがったり、という概念は無いように思います。
このPullRequestによって何をしたいのかがはっきり分かる表現で再度タイトルを考えてみていただけますでしょうか！

### コミットメッセージについて
コミットはそれぞれ変更の1単位になっている状態、またコミットメッセージからどんな変更がこのコミットで実施されたのかが分かる状態が理想的です。

拝見したところ、おそらく 
- 002e182 (Third commit...) がメインのi18nに関わる修正、
- 15a6686 (Fourth commit...) がrubocop適用のための諸々の修正

...ということかなと感じました。

変更内容の粒度自体はうまく分けられていると感じたので、コミットメッセージを再度、修正の内容が分かる形で書き直してみて欲しいです！

「このコミットがN回目のものであるか」は、今後何十回何百回とcommitを積み重ねていく上であまり重要ではない情報になっていきます。また「何月何日にコミットしたか」も、コミット自身が記録してくれているので(github上ではそのコミットを押すと、`〇〇 commited X days ago`   などと表記されていることが分かります)、コミットメッセージ自体に記録しなくても大丈夫です :+1: 

### i18n適用箇所全体的に
`t("title")` と `t 'title'` と `t('title')` の書き方が混じっているようです。
統一しておいたほうがあとから追加するときに、わずかですが迷わずにどんどん進むことができます。このリポジトリではどれを採用するか決めて統一してみてください。

以上です！ご確認お願いします〜 🙏

2020-09-21 06:48 UTC, betachelsea commented on Gemfile
> +  gem "rubocop-packaging"
他に development の group がすでにあるようなので、そちらにまとめていただきたいです。

2020-09-21 06:48 UTC, betachelsea commented on app/views/books/edit.html.erb
> +<h1><%=t('Editing Book') %></h1>
```suggestion
<h1><%= t('Editing Book') %></h1>
```

2020-09-21 06:48 UTC, betachelsea commented on app/views/books/index.html.erb
> +        <td><%= link_to  t('destroy'), book, method: :delete, data: { confirm: t('Are you sure?') } %></td>
```suggestion
        <td><%= link_to t('destroy'), book, method: :delete, data: { confirm: t('Are you sure?') } %></td>
```

2020-09-21 06:48 UTC, betachelsea commented on config/application.rb
> +    config.i18n.default_locale = :ja
```ruby
module BooksApp
  class Application < Rails::Application
  end
end
```

の定義はすでに同一ファイルのなかに出てきているので、既存の定義の中に config を追加する形でお願いします！

2020-09-21 06:48 UTC, betachelsea commented on config/locales/ja.yml
> +    Are you sure?: 削除していいですか？
yaml自体のルール的にはキーにスペース/記号/大文字小文字が含まれていても問題ないのですが、[rails-i18n](https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/ja.yml)を参考にするとキーはスネークケースで統一されています。なので、新しく追加したキーも rails-i18nにならってスネークケースでお願いします〜 🐍

2020-09-21 06:48 UTC, betachelsea commented on config/locales/ja.yml
> +
不要な末尾の空白は削除しちゃってください！ ✂️

2020-09-21 06:48 UTC, betachelsea commented on config/locales/ja.yml
> +    Created: 本を登録しました
この `created` に「本を登録しました」という表現が紐づいていますが、created だけだと、作ったものが違った時にうまく再利用できません。(例:  ユーザが登録成功したときに「本を登録しました」と表現すべきではない 🤔  )
この時便利なものとして lazy-lookup というものがあります。これを使うとview毎に区切って定義を分けることができます。将来定義を増やす時に備えて、うまくこれを使ってみた形に変えてみてもらえますでしょうか！

lazy-lookupについて(4.1.4 探索の「遅延」)
https://railsguides.jp/i18n.html#%E6%8E%A2%E7%B4%A2%E3%81%AE%E3%80%8C%E9%81%85%E5%BB%B6%E3%80%8D%EF%BC%88lazy-lookup%EF%BC%89

2020-09-21 12:30 UTC, hisaotoriyama commented on Gemfile
> +  gem "rubocop-packaging"
#### PullRequestのタイトルについて
I18n versionの意味は、今回の課題がi18の課題だったのでversionをつけたものでしたが、確かに紛らわしいので、add i18n functionと修正しました。

#### コミットメッセージについて
おっしゃる通りです。
002e182 (Third commit...) はi18n application
5a6686 (Fourth commit...) が rubocop application
に修正しました。

#### i18n適用箇所全体的に
特段理由はありませんが、t("title")に統一しました。

2020-09-21 12:32 UTC, hisaotoriyama commented on config/locales/ja.yml
> +
削除しました。

2020-09-21 12:34 UTC, hisaotoriyama commented on app/views/books/index.html.erb
> +        <td><%= link_to  t('destroy'), book, method: :delete, data: { confirm: t('Are you sure?') } %></td>
修正しました。細かなところまで申し訳ありません。

2020-09-21 12:41 UTC, hisaotoriyama commented on app/views/books/edit.html.erb
> +<h1><%=t('Editing Book') %></h1>
失礼しました。修正しました。他の箇所も確認しました

2020-09-22 04:28 UTC, hisaotoriyama commented on config/locales/ja.yml
> +
削除いたしました。

2020-09-22 04:31 UTC, hisaotoriyama commented on config/application.rb
> +    config.i18n.default_locale = :ja
修正いたしました。

2020-09-22 10:08 UTC, hisaotoriyama commented on config/locales/ja.yml
> +    Created: 本を登録しました
ご指導ありがとうございます。変更してみました。こういう感じでよろしいでしょうか。

2020-09-22 10:39 UTC, hisaotoriyama commented on config/locales/ja.yml
> +    Are you sure?: 削除していいですか？
下記でご指摘のlazy-lookupと併せ修正いたしました。

2020-09-22 10:39 UTC, hisaotoriyama commented on config/application.rb
> +    config.i18n.default_locale = :ja
修正いたしました。

2020-09-22 11:31 UTC, hisaotoriyama commented
#### PullRequestのタイトルについて
I18n versionの意味は、今回の課題がi18の課題だったのでversionをつけたものでしたが、確かに紛らわしいので、add i18n functionと修正しました。

#### コミットメッセージについて
おっしゃる通りです。
002e182 (Third commit...) はi18n application
5a6686 (Fourth commit...) が rubocop application
に修正しました。

#### i18n適用箇所全体的に
特段理由はありませんが、t("title")に統一しました。

2020-09-23 14:27 UTC, betachelsea requested changes
諸々修正ありがとうございます！
また、修正のためのgit操作に伴いyamlに問題のある表記が入ってしまったりなどあるようですので、再度ご確認をお願いします 🙏 

また、コミットメッセージ は毎回自分も悩むところではあるのですが、新しく追加されたコミットメッセージについてもちょっと気になる点があったので共有させてください。

```
change as per betachelsea-san instruction NO.1
```

コミットメッセージをなぜ頭を捻って書かねばならないのかというと、1年後2年後の自分や新規参入のチームメンバーのために必要だからです。今は全てのソースコードを把握できている状態で進捗されていると思うので、実感が沸きづらいかなと思うのですが、すっかり内容を忘れたあとにとある1行を変更したくなったとき(特に、とある1行が「あれ、無意味では？」と感じた時など)、その行の変更理由を知ることでその行を変更するか否かの判断材料にするケースがあります。どんなに無意味に見える行でも、その行が書かれた瞬間は何かしらの機能が求められていたはずです。そのため、その行を書いた人の意図を把握して初めて「この行は消しても良い/変更しても良い」という確実な判断を下すことができます。

個人的な昔のやらかしを共有しますと、うっかり消した後、まったく関係ないように見えた機能が動かなくなってしまったことがありました。ものすごく焦りました 😓 本来ならテストを充実させることで防げるミスですが、この時は不幸にもその対象機能のテストは存在しませんでした...。バグ調査時にコミットメッセージ を参考にすることで、削除してしまったが重要だった行を発見でき、解決に至りました。

今回のコミットについては自分(beta_chelsea)の指摘に対する変更として取りまとめていただきましたが、まったくの第三者がこのコミットを見た時に知りたいのは誰から受けた何回目の指摘だったかどうかではなく、 **どのような理由によって追加/変更/削除されたか**、ということです。

この情報をしっかり書こうとすると、1コミットが1つの理由によって構成されているのが理想的になってきます。
今回の例では、自分からは複数の指摘をさせていただいて、それがまとめてコミットされているために、`change as per betachelsea-san instruction NO.1` という表現になったのかなと思います。実際に分けようと思ったら、一例としてこうコミットを分けることが出来そうだなと思いました。

・Gemfileのgroupをまとめた
・`#t` ヘルパーのフォーマットを統一した
・config/application.rb の 重複した定義を統一した (*今回、gitの操作都合でうまくいっていない可能性があります)

最初はまどろっこしいなぁ、一括じゃダメなのかなぁと感じることも多いかと思いますが、適切な粒度にコミットを分けることができるというのはgitを利用した開発においてとても良い能力だと思いますので、次コミットからトレーニングだと思ってトライしてみてください！

### 参考
[コミットメッセージの書き方. 適切な情報を残そう | by risacan | Medium](https://medium.com/@risacan/%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9-64aeadd92057)
[誰にとってもわかりやすいGitのコミットメッセージを考える ｜ Tips Note by TAM](https://www.tam-tam.co.jp/tipsnote/program/post16686.html)
[[転載] gitにおけるコミットログ/メッセージ例文集100](https://gist.github.com/mono0926/e6ffd032c384ee4c1cef5a2aa4f778d7)

### 余談
人やチームによってはフォーマットを決めているというところもあり、フォーマットが決まっていたほうがスムーズに書きやすい、というものがあれば定めても問題ないと思います。もしくは、チームとして開発しているときにルールがすでに決まっていれば、従ったほうが良さそうです。今回は個人開発に近いので、お好きな形で書いていただいて大丈夫だとおもいます 🙆‍♂️ 

フォーマットがあってもなくても共通として重要なのは、「未来の自分/まったくの他人が読んだときにメッセージが役立つかどうか」です。また今回の変更のお願いでコミットを追加することになると思いますので、ぜひ意識してみてほしいです。
よろしくお願いします〜！

2020-09-23 14:27 UTC, betachelsea commented on config/locales/ja.yml
> +<<<<<<< HEAD
Gitのrebase? か何かのときのマークがコミットされてしまっていますね。
こちらyamlとして読み込めない原因となってしまうので削除をお願いします〜 ✂️ 

```
<<<<<<< HEAD
=======
>>>>>>> 15a6686edc6c1f86951df6de95305a9acf2eb864
```

2020-09-23 14:27 UTC, betachelsea commented on app/views/books/index.html.erb
> +        <td><%= link_to t("show") , book %></td>
気づいてしまいました!  👀 
```suggestion
        <td><%= link_to t("show"), book %></td>
```

2020-09-23 14:27 UTC, betachelsea commented on config/locales/ja.yml
> +        attributes:
フォームの見出しがi18n対応できていない様子です :eyes: 

<img width="336" alt="スクリーンショット 2020-09-23 22 04 55" src="https://user-images.githubusercontent.com/2603449/94020998-7bd7b780-fdee-11ea-92ea-37a1062d08be.png">


この時、次のようにすると特にフォームのviewを変更せずに( `<%= form.label :title %>` といった表現のままで )適用できます。

```yaml
ja:
    activerecord:
        attributes:
            book:
                title: タイトル
                memo: メモ
```

また、bookのtitle, memo といった表現をform以外の箇所で呼び出したい場合は、次の表現が使えます。
```ruby
Book.human_attribute_name("title")
```
詳しくはこちらをご覧ください！
[https://railsguides.jp/i18n.html#4.5active-recordモデルで翻訳を行なう](https://railsguides.jp/i18n.html#active-record%E3%83%A2%E3%83%87%E3%83%AB%E3%81%A7%E7%BF%BB%E8%A8%B3%E3%82%92%E8%A1%8C%E3%81%AA%E3%81%86)

2020-09-23 14:27 UTC, betachelsea commented on config/application.rb
> +    config.i18n.default_locale = :ja
11~23行目の中に入れるイメージですので、再度ご確認をお願いします〜 :pray:

2020-09-25 11:32 UTC, hisaotoriyama commented on config/application.rb
> +    config.i18n.default_locale = :ja
前回修正したつもりでしたが反映されていなかったようです。たびたびのご指摘恐れ入ります。

2020-09-25 11:34 UTC, hisaotoriyama commented on config/locales/ja.yml
> +
前回修正したつもりでしたが反映されていなかったようです。

2020-09-25 11:35 UTC, hisaotoriyama commented on config/locales/ja.yml
> +<<<<<<< HEAD
修正しました。前回のプロセスが変でした。

2020-09-25 11:45 UTC, hisaotoriyama commented on app/views/books/index.html.erb
> +        <td><%= link_to t("show") , book %></td>
細かいところまでのご指導ありがとうございます。修正しました。

2020-09-25 12:07 UTC, hisaotoriyama commented on config/locales/ja.yml
> +        attributes:
ありがとうございます。修正しました。
#### この時、次のようにすると特にフォームのviewを変更せずに( <%= form.label :title %> といった表現のままで )適用できます。
これはformの場合のみに許されたテクニックなのでしょうか？

2020-09-25 14:31 UTC, betachelsea commented on config/locales/ja.yml
> +        attributes:
formのlabelのほかには、**エラー文を表示させるシーン**ですとこの `ja.activerecord.attributes.book.title`  や `ja.activerecord.attributes.book.memo` といった指定が役立ちます。
今回導入してくださった `config/locales/ja.yml` に次のような表記があります。

```
blank: を入力してください
```
こちらはエラーメッセージの翻訳の一部で、「バリデーションエラー」の対応で利用するのですが、この時実際の表示では上記の指定ができていると「タイトルを入力してください」といった表示になります。(逆にできていないと「Titleを入力してください」になります。

formのlabelやエラーメッセージでこの翻訳が使えるのは、Model(Book)のデータが仲介役となって参照できる仕組みになっているからです。

表組みなどで使われている `<th>Title</th>` は残念ながらただの文字列でModelと関連していないので、もしこのあたりを翻訳で `ja.activerecord.attributes.book.~` と紐付けたい場合は、次のようにする必要があります。

```
<th><%= Book.human_attribute_name("title") %></th>
```

2020-09-26 02:36 UTC, merged